// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type LoginWithReservationResponse struct {
	Token       string       `json:"token"`
	Reservation *Reservation `json:"reservation"`
}

type Mutation struct {
}

type NewReservation struct {
	FirstName   *string   `json:"firstName,omitempty"`
	LastName    string    `json:"lastName"`
	Amount      int32     `json:"amount"`
	PhoneNumber string    `json:"phoneNumber"`
	Email       string    `json:"email"`
	ReserveAt   time.Time `json:"reserveAt"`
	Notes       *string   `json:"notes,omitempty"`
}

type Query struct {
}

type Reservation struct {
	ID          string            `json:"id"`
	FirstName   *string           `json:"firstName,omitempty"`
	LastName    string            `json:"lastName"`
	PhoneNumber string            `json:"phoneNumber"`
	Email       string            `json:"email"`
	Amount      int32             `json:"amount"`
	CreatedAt   time.Time         `json:"createdAt"`
	ReserveAt   time.Time         `json:"reserveAt"`
	Status      ReservationStatus `json:"status"`
	Notes       *string           `json:"notes,omitempty"`
}

type ReservationEventPayload struct {
	Reservation *Reservation              `json:"reservation"`
	Event       ReservationEventBroadcast `json:"event"`
}

type ReservationFilter struct {
	FirstName   *string            `json:"firstName,omitempty"`
	LastName    *string            `json:"lastName,omitempty"`
	ID          *string            `json:"id,omitempty"`
	Status      *ReservationStatus `json:"status,omitempty"`
	Amount      *int32             `json:"amount,omitempty"`
	DateFrom    *time.Time         `json:"dateFrom,omitempty"`
	DateTo      *time.Time         `json:"dateTo,omitempty"`
	Email       *string            `json:"email,omitempty"`
	PhoneNumber *string            `json:"phoneNumber,omitempty"`
}

type ReservationInfo struct {
	TotalReservation          int32                    `json:"totalReservation"`
	TotalPerson               int32                    `json:"totalPerson"`
	TotalBigReservation       int32                    `json:"totalBigReservation"`
	TotalOpenReservation      int32                    `json:"totalOpenReservation"`
	TotalConfirmedReservation int32                    `json:"totalConfirmedReservation"`
	TotalCanceledReservation  int32                    `json:"totalCanceledReservation"`
	ByHours                   []*ReservationInfoByHour `json:"byHours"`
}

type ReservationInfoByHour struct {
	TotalReservation    int32     `json:"totalReservation"`
	TotalPerson         int32     `json:"totalPerson"`
	TotalBigReservation int32     `json:"totalBigReservation"`
	StartsAt            time.Time `json:"startsAt"`
	EndsAt              time.Time `json:"endsAt"`
}

type Subscription struct {
}

type UpdateReservation struct {
	ID          string     `json:"id"`
	FirstName   *string    `json:"firstName,omitempty"`
	LastName    *string    `json:"lastName,omitempty"`
	PhoneNumber *string    `json:"phoneNumber,omitempty"`
	Email       *string    `json:"email,omitempty"`
	Amount      *int32     `json:"amount,omitempty"`
	ReserveAt   *time.Time `json:"reserveAt,omitempty"`
	Notes       *string    `json:"notes,omitempty"`
}

type ReservationEventBroadcast string

const (
	ReservationEventBroadcastCreated   ReservationEventBroadcast = "CREATED"
	ReservationEventBroadcastUpdated   ReservationEventBroadcast = "UPDATED"
	ReservationEventBroadcastCanceled  ReservationEventBroadcast = "CANCELED"
	ReservationEventBroadcastConfirmed ReservationEventBroadcast = "CONFIRMED"
	ReservationEventBroadcastDeclined  ReservationEventBroadcast = "DECLINED"
)

var AllReservationEventBroadcast = []ReservationEventBroadcast{
	ReservationEventBroadcastCreated,
	ReservationEventBroadcastUpdated,
	ReservationEventBroadcastCanceled,
	ReservationEventBroadcastConfirmed,
	ReservationEventBroadcastDeclined,
}

func (e ReservationEventBroadcast) IsValid() bool {
	switch e {
	case ReservationEventBroadcastCreated, ReservationEventBroadcastUpdated, ReservationEventBroadcastCanceled, ReservationEventBroadcastConfirmed, ReservationEventBroadcastDeclined:
		return true
	}
	return false
}

func (e ReservationEventBroadcast) String() string {
	return string(e)
}

func (e *ReservationEventBroadcast) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReservationEventBroadcast(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReservationEventBroadcast", str)
	}
	return nil
}

func (e ReservationEventBroadcast) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReservationEventBroadcast) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReservationEventBroadcast) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReservationStatus string

const (
	ReservationStatusOpen      ReservationStatus = "OPEN"
	ReservationStatusConfirmed ReservationStatus = "CONFIRMED"
	ReservationStatusCanceled  ReservationStatus = "CANCELED"
	ReservationStatusDeclined  ReservationStatus = "DECLINED"
)

var AllReservationStatus = []ReservationStatus{
	ReservationStatusOpen,
	ReservationStatusConfirmed,
	ReservationStatusCanceled,
	ReservationStatusDeclined,
}

func (e ReservationStatus) IsValid() bool {
	switch e {
	case ReservationStatusOpen, ReservationStatusConfirmed, ReservationStatusCanceled, ReservationStatusDeclined:
		return true
	}
	return false
}

func (e ReservationStatus) String() string {
	return string(e)
}

func (e *ReservationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReservationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReservationStatus", str)
	}
	return nil
}

func (e ReservationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReservationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReservationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
